
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 09 19:48:58 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 18;
  public static final int LTE = 33;
  public static final int CHAR = 51;
  public static final int CONST = 8;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 43;
  public static final int SEMI = 39;
  public static final int MINUS = 24;
  public static final int RPAREN = 44;
  public static final int AND = 34;
  public static final int LT = 32;
  public static final int RECORD = 22;
  public static final int OR = 35;
  public static final int BOOL = 50;
  public static final int COMMA = 41;
  public static final int CLASS = 5;
  public static final int INC = 37;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int IF = 9;
  public static final int THIS = 19;
  public static final int DOT = 42;
  public static final int LSQBR = 45;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 36;
  public static final int SUPER = 20;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int EQEQ = 28;
  public static final int NUMBER = 49;
  public static final int MOD = 27;
  public static final int BREAK = 4;
  public static final int IDENT = 3;
  public static final int VOID = 16;
  public static final int GTE = 31;
  public static final int COLON = 40;
  public static final int LBRACE = 47;
  public static final int ELSE = 7;
  public static final int ENUM = 6;
  public static final int READ = 14;
  public static final int GOTO = 21;
  public static final int WHILE = 11;
  public static final int RBRACE = 48;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int RSQBR = 46;
  public static final int DEC = 38;
  public static final int GT = 30;
  public static final int PRINT = 13;
  public static final int DO = 10;
}

