
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 10 14:42:42 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 17;
  public static final int LTE = 32;
  public static final int CHAR = 51;
  public static final int CONST = 7;
  public static final int NOTEQUAL = 28;
  public static final int LPAREN = 42;
  public static final int SEMI = 38;
  public static final int MINUS = 23;
  public static final int RPAREN = 43;
  public static final int AND = 33;
  public static final int LT = 31;
  public static final int RECORD = 21;
  public static final int OR = 34;
  public static final int BOOL = 49;
  public static final int COMMA = 40;
  public static final int CLASS = 4;
  public static final int INC = 36;
  public static final int DIV = 25;
  public static final int PLUS = 22;
  public static final int IF = 8;
  public static final int THIS = 18;
  public static final int DOT = 41;
  public static final int LSQBR = 44;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 35;
  public static final int SUPER = 19;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int EQEQ = 27;
  public static final int NUMBER = 48;
  public static final int MOD = 26;
  public static final int IDENT = 50;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int GTE = 30;
  public static final int COLON = 39;
  public static final int LBRACE = 46;
  public static final int ELSE = 6;
  public static final int ENUM = 5;
  public static final int READ = 13;
  public static final int GOTO = 20;
  public static final int WHILE = 10;
  public static final int RBRACE = 47;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int RSQBR = 45;
  public static final int DEC = 37;
  public static final int GT = 29;
  public static final int PRINT = 12;
  public static final int DO = 9;
}

